### PR TITLE
Replace d.py with hikari and hikari-tanjun

### LINKED ISSUE #4: Migrate Dayong's design model and implement slash commands
The sole maintainer of discord.py has [ceased](https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1) the development of their API wrapper. This is my first time making a complete discord bot, so I wasn't aware of this matter.

The reason I chose discord.py was because of its popularity and that it was a fast and mature library. Now that discord.py is essentially dead, we're left with a few options:

1. Rebuild the bot in another language.
2. Rebuild the bot with another library.
3. Extend discord.py to support slash commands.

If you read Danny's announcement, Discord is forcing bot developers to use slash commands. Dayong will die in 8 or 9 months if we continue using discord.py's design model.

Regarding our remaining options, from a project maintainer's point of view, the first one sounds like our top choice, but we don't have to abandon Python just yet. Personally, I think the second or third is our best option. For number 2, I'm looking into other libraries, such as [hikari](https://github.com/hikari-py/hikari), which is starting to gain traction after the announcement. For number 3, there's [discord-interactions](https://github.com/goverfl0w/discord-interactions), which is a discord.py extension for supporting slash commands.

### PR DESCRIPTION
**Pull request by huenique**
Resolves #4

After much deliberation, I've decided to rebuild Dayong with a different library, [hikari](https://hikari-py.github.io/hikari/).

Extending discord.py was initially our first choice. Developing, testing, and implementing the extension would take months, so that was out. The obvious, best step was to use already existing libraries for that purpose. The best option was [discord-interactions](https://github.com/goverfl0w/discord-interactions) out there, which seemed like the answer at first, but after taking a peek at the source code of the current stable build, I determined it wasn’t. I’d rather not deal with endless lines of inefficient spaghetti code. The unstable build is a lot better, but who knows when that'll be ready.

Active forks of d.py do exist, but they were still in the process of monkey-patching, and devs were still developing and testing the interactions module. Moreover, none of them seem to be fully supportive of type hints from python 3.9 and above.

There are a few minor issues regarding the usage of [hikari](https://hikari-py.github.io/hikari/). It particularly involves newbie python developers or maybe beginner programmers in general. I’m mainly concerned with its documentation. It’s not very newbie-friendly, as compared to discord.py's documentation. New contributors will definitely have a hard time implementing features and fixing bugs because they’ll be having a hard time finding the methods and classes they need, but only until they get used to it.

### CODE REVIEW

**Comment by huenique** [comment]
I forgot to mention. I added [hikari-tanjun](https://github.com/FasterSpeeding/Tanjun) as a supplement to ease some future headaches that would come from trying to develop features for Dayong.

**Comment by huenique** [comment]
I've pretty much ported the base features. I think it's ready to receive feature requests via issues at main. I also think it's ready for production since we're already able to implement and use slash commands.

**Comment by vinzvinci** [comment]
Looks good, but I want @chraem to decide on these changes.

**Comment by chraem** [comment]
LGTM 😄👍🏼

**Pull request merged**
